build:
  image: fracting/msys32
  shell: msys32
  commands:
    - export RUNTEST=$$runtest
    - drone/build.sh

notify:
  irc:
    prefix: build
    nick: MSYS2-packages
    channel: msys2
    server:
      host: irc.oftc.net
      port: 6667

matrix:
  runtest:
    - false
    - true # allow failures
